networks:
  default:
    driver: bridge
  proxy:
    external: true

services:

## Database
  v3sm-pg:
    image: postgres:16-alpine
    container_name: v3sm-pg
    ports:
      - "9923:5432"
    environment:
      POSTGRES_USER: ${PG_U}
      POSTGRES_PASSWORD: ${PG_P}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./pgdb:/var/lib/postgresql/data
      - ./api/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - default

## Redis
  v3sm-redis:
    image: redis:alpine
    container_name: v3sm-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - default
    expose:
      - "6379"


## Main API service
  v3sm-api:
    build: ./api
    container_name: v3sm-api
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - PG_HOST=v3sm-pg
      - PG_PORT=5432
      - PG_U=${PG_U}
      - PG_P=${PG_P}
      - PG_DB=${PG_DB}
      - REDIS_HOST=v3sm-redis
      - REDIS_PORT=6379
      - API_KEY_TEST=${API_KEY_TEST}
      - API_ALLOWED_LOCAL_IPS=${API_ALLOWED_LOCAL_IPS}
      - JWT_SECRET=${JWT_SECRET}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_BOT_ID=${DISCORD_BOT_ID}
      - DISCORD_BOT_SECRET=${DISCORD_BOT_SECRET}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - DISCORD_SERVER_ID=${DISCORD_SERVER_ID}
      - DISCORD_ADMIN_ROLE_ID=${DISCORD_ADMIN_ROLE_ID}
      - DISCORD_MANAGER_ROLE_ID=${DISCORD_MANAGER_ROLE_ID}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - v3sm-pg
      - v3sm-redis
    restart: unless-stopped
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.v3smapi.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.v3smapi.entrypoints=https"
      - "traefik.http.routers.v3smapi.tls=true"
      - "traefik.http.routers.v3smapi.tls.certresolver=letsencrypt"
      - "traefik.http.routers.v3smapi.service=v3smapi"
      - "traefik.http.services.v3smapi.loadbalancer.server.port=3000"
      - "traefik.http.routers.v3smapi.middlewares=api-stripprefix"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"

## Main Map Client - THE STAR OF THE SHOW!
  v3sm-client:
    build: ./client
    command: bun run dev
    container_name: v3sm-client
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://${DOMAIN}/api/graphql
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - v3sm-api
    restart: unless-stopped
    networks:
      - default
      - proxy
    labels:
      # Main domain - highest priority route
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.v3smclient.rule=Host(`${DOMAIN}`) && !PathPrefix(`/api`) && !PathPrefix(`/admin`)"
      - "traefik.http.routers.v3smclient.entrypoints=https"
      - "traefik.http.routers.v3smclient.tls=true"
      - "traefik.http.routers.v3smclient.tls.certresolver=letsencrypt"
      - "traefik.http.routers.v3smclient.service=v3smclient"
      - "traefik.http.services.v3smclient.loadbalancer.server.port=3000"
      - "traefik.http.routers.v3smclient.middlewares=client-headers"
      - "traefik.http.middlewares.client-headers.headers.customrequestheaders.X-Forwarded-Proto=https"

## Admin dashboard
  v3sm-admin:
    build: ./admin
    command: bun run dev
    container_name: v3sm-admin
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://${DOMAIN}/api
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./admin:/app
      - /app/node_modules
    depends_on:
      - v3sm-api
    restart: unless-stopped
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.v3smadmin.rule=Host(`${DOMAIN}`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.v3smadmin.entrypoints=https"
      - "traefik.http.routers.v3smadmin.tls=true"
      - "traefik.http.routers.v3smadmin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.v3smadmin.service=v3smadmin"
      - "traefik.http.services.v3smadmin.loadbalancer.server.port=3000"
      - "traefik.http.routers.v3smadmin.middlewares=admin-headers"
      - "traefik.http.middlewares.admin-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.admin-headers.headers.customresponseheaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.admin-headers.headers.customresponseheaders.Access-Control-Allow-Origin=*"
      - "traefik.http.middlewares.admin-headers.headers.customresponseheaders.Access-Control-Allow-Methods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.admin-headers.headers.customresponseheaders.Access-Control-Allow-Headers=Content-Type,Authorization"
      - "traefik.http.middlewares.admin-headers.headers.customresponseheaders.Cache-Control=no-cache, no-store, must-revalidate"
      - "traefik.http.middlewares.admin-headers.headers.customresponseheaders.Pragma=no-cache"
      - "traefik.http.middlewares.admin-headers.headers.customresponseheaders.Expires=0"

volumes:
  redis_data: