networks:
  proxy:
    external: true

services:
  devsoulmap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devsoulmap
    command: bun dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_PORT=${CLIENT_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - DOMAIN=${DOMAIN}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - proxy
      - default
    restart: always
    labels:
      # Enable Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      
      # Single service for the domain - all requests to the client
      - "traefik.http.services.devsoulmap.loadbalancer.server.port=${CLIENT_PORT}"
      
      # Frontend for both HTTP and HTTPS
      - "traefik.http.routers.devsoulmap.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.devsoulmap.entrypoints=http,https"
      - "traefik.http.routers.devsoulmap.tls=true"
      - "traefik.http.routers.devsoulmap.tls.certresolver=letsencrypt"
      
      # Fix for websocket connections
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.X-Forwarded-Host=${DOMAIN}"
      - "traefik.http.routers.devsoulmap.middlewares=websocket"
    depends_on:
      devsm-pg:
        condition: service_healthy
  
  devsm-pg:
    image: postgres:latest
    container_name: devsoulmap-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "15432:5432"  # PostgreSQL port
    networks:
      - default
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
