networks:
  proxy:
    external: true

services:
  soulmap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soulmap
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=production
    networks:
      - proxy
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.soulmap-ssl.tls.certresolver=letsencrypt
      - traefik.http.routers.soulmap-nossl.rule=Host(`soulmap.avakot.org`)
      - traefik.http.routers.soulmap-nossl.service=soulmap
      - traefik.http.routers.soulmap-nossl.entrypoints=http
      - traefik.http.services.soulmap.loadbalancer.server.port=5173
  
  soulmapbot:
    build:
      context: ./discord_bot/
      dockerfile: Dockerfile
    container_name: soulmapbot
    command: npm run dev
    environment:
      - DISCORD_TOKEN=${discord_bot_token}
      - CHANNEL_ID=1359034600969601234 
      - ADMIN_ROLE_ID=1310672502355267697
    volumes:
      - ./discord_bot/data:/app/data
      - ./discord_bot/index.js:/app/index.js
      - ./discord_bot/package.json:/app/package.json
      - ./discord_bot/database.js:/app/database.js
      - ./src/mapversion.yml:/app/src/mapversion.yml
    restart: always