networks:
  proxy:
    external: true

services:
  soulmap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soulmap
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.soulmap.rule=Host(`soulmap.ascriptingoreo.online`)
      - traefik.http.services.soulmap.loadbalancer.server.port=5173
      - traefik.http.routers.soulmap.entrypoints=https
      - traefik.http.routers.soulmap.tls=true
      - traefik.http.routers.soulmap.tls.certresolver=letsencrypt
      