networks:
  proxy:
    external: true

services:
  soulmap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soulmap
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - proxy
    labels:
      # First domain with SSL
      - traefik.enable=true
      - traefik.http.routers.soulmap-ssl.rule=Host(`soulmap.ascriptingoreo.online`)
      - traefik.http.routers.soulmap-ssl.service=soulmap
      - traefik.http.routers.soulmap-ssl.entrypoints=https
      - traefik.http.routers.soulmap-ssl.tls=true
      - traefik.http.routers.soulmap-ssl.tls.certresolver=letsencrypt
      
      # Second domain without SSL (for Cloudflare)
      - traefik.http.routers.soulmap-nossl.rule=Host(`soulmap.avakot.org`)
      - traefik.http.routers.soulmap-nossl.service=soulmap
      - traefik.http.routers.soulmap-nossl.entrypoints=http
      
      # Shared service configuration
      - traefik.http.services.soulmap.loadbalancer.server.port=5173